; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:deskbuddy]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board = nodemcu-32s
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	adafruit/Adafruit GFX Library@^1.12.5
	adafruit/Adafruit SH110X@^2.1.14
